version: "3.9"
services:
  traefik:
    image: traefik:v2.10
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres/postgres
      - REDIS_URL=redis://redis:6379/0
      - AUTH_TOKEN=${AUTH_TOKEN:-secret-token}
    depends_on:
      - postgres
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${BRANCH_NAME}.app.a-server.ch`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    networks:
      - web

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${BRANCH_NAME}.app.a-server.ch`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - web

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - web

  worker:
    build: ./backend
    command: python -m app.worker
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres/postgres
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  postgres_data:
